### ISSUE TITLE
Can't find trailing parenthesis for function 'DIALPLAN_EXISTS(internal,74952293042,1'?

### ISSUE THREAD

**Issue by ivstep** [mikopbx/ModuleUsersGroups#17]
Версия 1.48

Строка с ошибкой:

same => n,ExecIf($[ ${srcIsolate} && ${dstIsolateGroup} != 1 && dstIsolate != 1 && ${DIALPLAN_EXISTS(internal,${EXTEN},1} != 1 ]?Set(srcIsolate=0))

**Comment by boffart** [comment]
https://qa.mikopbx.ru/14558/странные-сообщения-в-логах
это исправлено, но еще не в релизе.
